// src/components/hello.vue

<script lang="js">
    import {helloSubject} from '../stores/hello.store';
    import {searchSubject} from '../stores/search.store';


    export default {
        name: 'VueHello',
        props: {
            name: String
        },
        data() {
            return {
                yo: '',
                search: '',
            }
        },
        methods: {
            yoFrom() {
                helloSubject.next('Yo from Vue click');
            }
        },
        mounted() {
            helloSubject.subscribe(x => this.yo = x);
            searchSubject.subscribe(x => this.search = x);
        }
    }
</script>

<template>
    <h2 class="text-green-500">Hello {{name}}</h2>
    <button @click="yoFrom()">Yo</button>
    <p>{{yo}}</p>
    <p>{{search}}</p>
</template>

// src/components/hello.jsx
import { useEffect, useState } from "react";
import { helloSubject } from "../stores/hello.store";
import { searchSubject } from '../stores/search.store';

const ReactHello = ({ name }) => {
  const [yoFrom, setYoFrom] = useState("");
  const [search, setSearch] = useState("");
  useEffect(() => {
    helloSubject.subscribe((x) => setYoFrom(x));
    searchSubject.subscribe((x) => setSearch(x));
  });
  function yo() {
    helloSubject.next("Yo from React click");
  }

  return (
    <>
      <h2 className="text-blue-500">Hello {name}</h2>
      <button onClick={yo}>Yo</button>
      <p>{yoFrom}</p>
      <p>{search}</p>
    </>
  );
};

export default ReactHello;
