// src/components/hello.component.ts
import { Component, inject, NgZone } from '@angular/core';
import { enterZone } from '../pipe/angular-enter-zone';
import {helloSubject} from '../stores/hello.store';
@Component({
  selector: 'app-hello',
  standalone: true,
  template: `
    <h1 class="text-red-500">Hello {{title}}</h1>
    <button (click)="toggle()">Yo</button>
    <p>{{yo}}</p>

  `,
})
export class AngularHello {
  yo = '';
  title = 'Angular';
  private readonly ngZone = inject(NgZone);

  constructor() {
    helloSubject.pipe(enterZone(this.ngZone)).subscribe(x => this.yo = x);
  }

  toggle() {
    helloSubject.next('Yo from Angular');
  }
}

// src/components/hello.jsx

import React, { useEffect, useState } from "react";
import {helloSubject} from '../stores/hello.store';

export function ReactHello() {
    const [yoFrom, setYoFrom] = useState('');
    const title = 'React';
    useEffect(() => {
        helloSubject.subscribe(x => setYoFrom(x))
    });

    function yo() {
        helloSubject.next('Yo from React');
    }
  
    return (
        <>
            <h1 className="text-blue-500">Hello {title}</h1>
            <button onClick={yo}>Yo</button>
            <p>{yoFrom}</p>
        </>
    );

    
  }
